export const GET_PRODUCTS_DATA_INPROGRESS = "GET_PRODUCT_DATA_INPROGRESS";
export const GET_PRODUCTS_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCTS_DATA_FAILURE = "GET_PRODUCT_DATA_FAILURE";

export const GET_PRODUCT_INFO_INPROGRESS = "GET_PRODUCT_INFO_INPROGRESS";
export const GET_PRODUCT_INFO_SUCCESS = "GET_PRODUCT_INFO_SUCCESS";
export const GET_PRODUCT_INFO_FAILURE = "GET_PRODUCT_INFO_FAILURE";

export const SET_PAGE = "SET_PAGE";

export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const INCREASE_CART_ITEM_COUNT = "INCREASE_CART_ITEM_COUNT";

export const DECREASE_CART_ITEM_COUNT = "DECREASE_CART_ITEM_COUNT";

export const EMPTY_CART = "EMPTY_CART";
